install.packages('BiocManager', repos="https://cloud.r-project.org")
install.packages('ggfortify', repos="https://cloud.r-project.org")
install.packages('data.table', repos="https://cloud.r-project.org")
BiocManager::install('edgeR', update=FALSE)
BiocManager::install('dplyr', update=FALSE)
BiocManager::install('statmod', update=FALSE)
#BiocManager::install('DESeq2', update=FALSE)
#BiocManager::install('ensembldb', update=FALSE)
#BiocManager::install('tximport', update=FALSE)
#BiocManager::install('org.Hs.eg.db', update=FALSE)
BiocManager::install('org.Mm.eg.db', update=FALSE)
BiocManager::install('topGO', update=FALSE)
#BiocManager::install('goseq', update=FALSE)
#BiocManager::install('clusterProfiler', update=FALSE)
#BiocManager::install('GOplot', update=FALSE)
#BiocManager::install('dendextend', update=FALSE)
#BiocManager::install('mclust', update=FALSE)
# BiocManager::install('biclust', update=FALSE)
# BiocManager::install('NMF', update=FALSE)
# BiocManager::install('breakpoint', update=FALSE)
# BiocManager::install('affy', update=FALSE)
# BiocManager::install('GEOquery', update=FALSE)
# BiocManager::install('rWikiPathways', update=FALSE)
# BiocManager::install('RCy3', update=FALSE)
# BiocManager::install('sva', update=FALSE)
BiocManager::install('openxlsx', update=FALSE)
BiocManager::install('venn', update=FALSE)
# BiocManager::install('cqn', update=FALSE)
# BiocManager::install('ballgown', update=FALSE)
# BiocManager::install('AnnotationHub', update=FALSE)
# BiocManager::install('knitr', update=FALSE)
# BiocManager::install('pheatmap', update=FALSE)
# BiocManager::install('TMixClust', update=FALSE)
# BiocManager::install('WGCNA', update=FALSE)
# BiocManager::install('affy', update=FALSE)
# BiocManager::install('oligo', update=FALSE)
# BiocManager::install('arrayQualityMetrics', update=FALSE)
# BiocManager::install('SPIA', update=FALSE)
# BiocManager::install('graphite', update=FALSE)






